[package]
name = "wptreport"
version = "0.1.0"
authors = ["James Graham <james@hoppipolla.co.uk>"]
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
